apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  config.json: |
    {
      "listener": {
        "tcp":{
          "address": "127.0.0.1:8200",
          "tls_disable": 0,
          "tls_cert_file": "/etc/tls/vault.pem",
          "tls_key_file": "/etc/tls/vault-key.pem"
        }
      },
      "storage": {
        "consul": {
          "address": "consul:8500",
          "path": "vault/",
          "disable_registration": "true",
          "ha_enabled": "true"
        }
      },
      "ui": true
    }
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          command: ["vault", "server", "-config", "/vault/config/config.json"]
          image: "vault:0.11.5"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: configurations
              mountPath: /vault/config/config.json
              subPath: config.json
            - name: vault
              mountPath: /etc/tls
        - name: consul-vault-agent
          image: "consul:1.8.3"
          env:
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul
                  key: gossip-encryption-key
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-config-file=/consul/myconfig/config.json"
            - "-domain=cluster.local"
            - "-datacenter=dc1"
            - "-disable-host-node-id"
            - "-node=vault-1"
          volumeMounts:
            - name: config
              mountPath: /consul/myconfig
            - name: tls
              mountPath: /etc/tls
      volumes:
        - name: configurations
          configMap:
            name: vault
        - name: config
          configMap:
            name: consul
        - name: tls
          secret:
            secretName: consul
        - name: vault
          secret:
            secretName: vault
