apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-poker
data:
  config.yaml: |
    matchmaker_signing_key: pokertest
    http_port: 7654
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: royalafg-poker-autoscaler
spec:
  fleetName: royalafg-poker
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 1
      maxReplicas: 5 
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: royalafg-poker
  labels:
    name: "royalafg-poker"
    game: "poker"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "royalafg-poker"
        game: "poker"
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7654
          protocol: TCP
      health:
        initialDelaySeconds: 20
        periodSeconds: 60
        failureThreshold: 10
          
      template:
        metadata:
          labels:
            app: royalafg-poker-gameserver
          annotations:
            'consul.hashicorp.com/connect-inject': "false"
        spec:
          containers:
            - name: royalafg-poker
              image: docker.io/johnnys318/royalafg_poker:latest
              volumeMounts:
                - name: royalafg-poker-config
                  mountPath: "/etc/royalafg-poker"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"                       
          volumes:
            - name: royalafg-poker-config
              configMap:
                name: royalafg-poker
        