apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
    role: master
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
    name: client
---
apiVersion: apps/v1  # API version
kind: Deployment
metadata:
  name: redis-master # Unique name for the deployment
  labels:
    app: redis       # Labels to be applied to this deployment
spec:
  selector:
    matchLabels:     # This deployment applies to the Pods matching these labels
      app: redis
      role: master
      tier: backend
  replicas: 1        # Run a single pod in the deployment
  template:          # Template for the pods that will be created by this deployment
    metadata:
      labels:        # Labels to be applied to the Pods in this deployment
        app: redis
        role: master
        tier: backend
    spec:            # Spec for the container which will be run inside the Pod.
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-poker-matchmaker
data:
  config.yaml: |
    jwt_signing_key: testsecret
    redis_url: redis.default.svc.cluster.local:6379
    matchmaker_signing_key: pokertest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: royalafg-poker-matchmaker
spec:
  rules:
    - host: royalafg.games
      http:
          paths:
            - path: "/api/poker"
              pathType: Exact
              backend:
                service:
                  name: royalafg-poker-matchmaker
                  port:
                    number: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: royalafg-poker-matchmaker
spec:
  type: ClusterIP
  selector:
    app: royalafg-poker-matchmaker
  ports:
  - port: 8081
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: royalafg-poker-matchmaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: royalafg-poker-matchmaker-access
subjects:
  - kind: User
    name: system:serviceaccount:default:royalafg-poker-matchmaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-allocator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-poker-matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-poker-matchmaker
  template:
    metadata:
      labels:
        app: royalafg-poker-matchmaker
    spec:
      serviceAccountName: royalafg-poker-matchmaker
      containers:
      - name: royalafg-poker-matchmaker
        image: docker.io/johnnys318/royalafg_poker_match:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
          - protocol: TCP
            containerPort: 8080 
        volumeMounts:
          - mountPath: "/etc/royalafg-poker-matchmaker"
            name: royalafg-poker-matchmaker-config
      volumes:
        - name: royalafg-poker-matchmaker-config
          configMap:
              name: royalafg-poker-matchmaker

