apiVersion: v1
kind: Service
metadata:
  name: royalafg-user
  namespace: royalafg
spec:
  selector:
    app: royalafg-user
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-user
  namespace: royalafg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-user
  namespace: royalafg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-user
  template:
    metadata:
      labels:
        app: royalafg-user
    spec:
      serviceAccountName: royalafg-user
      containers:
        - name: royalafg-user
          imagePullPolicy: Always
          image: docker.io/johnnys318/royalafg-user:latest
          resources:
            requests:
              memory: 10Mi
              cpu: 100m
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: RYLUSER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: royalafg-user
                  key: jwt-key
            - name: RYLUSER_MONGODBURL
              valueFrom:
                secretKeyRef:
                  key: db-url
                  name: royalafg-user
            - name: RYLUSER_USER-PEPPER
              valueFrom:
                secretKeyRef:
                  key: user-pepper
                  name: royalafg-user
          volumeMounts:
            - name: royalafg-user-serviceConfig
              mountPath: "/etc/royalafg-user" 

      volumes:
        - name:  royalafg-user-serviceConfig
          configMap:
              name: royalafg-user