apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: royalafg-auth
spec:
  rules:
    - host: troyalafg.games
      http:
        paths:
          - path: /account
            pathType: Prefix
            backend:
              service:
                name: royalafg-auth
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: royalafg-auth
spec:
  selector:
    app: royalafg-auth
  ports:
    - name: web
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-auth
data:
  config.yaml: |
    jwt_signing_key: testsecret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-auth
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "royalafg-user:8080"
      labels:
        app: royalafg-auth
        service: auth
    spec:
      serviceAccountName: royalafg-auth
      containers:
        - name: royalafg-auth
          image: docker.io/johnnys318/royalafg_auth:latest
          resources:
              requests:
                memory: 10Mi
                cpu: 80m
          ports:
            - protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: royalafg-auth-config
              mountPath: "/etc/royalafg-auth"
      volumes:
        - name: royalafg-auth-config
          configMap:
            name: royalafg-auth
