apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: royalafg-user-mongo
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  persistent: true
  exposedExternally: true
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: royalafg-user-mongo
        key: password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin